##Theoretical Questions :

Q1 - Explain the purpose and advantages of Numpy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans - **NumPy: The Powerhouse of Scientific Computing in Python**

NumPy, short for Numerical Python, is a fundamental library for scientific computing in Python. It provides efficient array manipulation and mathematical functions, significantly boosting Python's capabilities for numerical operations.

**Key Purposes of NumPy:**

1. **Efficient Array Handling:**
   - **Multidimensional Arrays:** NumPy introduces the `ndarray` object, which represents n-dimensional arrays. These arrays are more efficient than Python's built-in lists, especially for large datasets.
   - **Vectorized Operations:** NumPy allows for vectorized operations, meaning operations are performed element-wise on entire arrays, eliminating the need for explicit loops. This significantly speeds up computations.

2. **Mathematical Functions:**
   - **Broadcasting:** NumPy's broadcasting rules enable operations between arrays of different shapes, simplifying complex calculations.
   - **Universal Functions (UFuncs):** NumPy provides a rich set of ufuncs for mathematical operations like trigonometric functions, logarithmic functions, and statistical calculations.
   - **Linear Algebra:** NumPy offers efficient linear algebra routines, including matrix multiplication, inversion, and eigenvalue decomposition.

**Advantages of NumPy:**

- **Performance:** NumPy's C-based implementation and vectorization techniques make it significantly faster than pure Python for numerical operations.
- **Ease of Use:** NumPy's intuitive syntax and high-level abstractions simplify complex numerical computations.
- **Integration with Other Libraries:** NumPy serves as the foundation for many other scientific Python libraries, such as SciPy, Pandas, and Matplotlib.
- **Large Community and Support:** NumPy has a large and active community, providing extensive documentation, tutorials, and support resources.

**How NumPy Enhances Python's Numerical Capabilities:**

- **Efficient Data Structures:** NumPy's `ndarray` provides a powerful and efficient data structure for storing and manipulating numerical data.
- **Vectorized Operations:** NumPy's vectorized operations allow for concise and efficient code, avoiding explicit loops and significantly improving performance.
- **Broadcasting:** NumPy's broadcasting rules enable flexible and efficient operations between arrays of different shapes.
- **Mathematical Functions:** NumPy offers a comprehensive set of mathematical functions, including linear algebra, statistical functions, and more.
- **Integration with Other Libraries:** NumPy's integration with other scientific Python libraries enables seamless data analysis and visualization workflows.

In conclusion, NumPy is an indispensable tool for scientific computing and data analysis in Python. Its efficient array handling, powerful mathematical functions, and seamless integration with other libraries make it a cornerstone of the Python scientific ecosystem.

Q2 - Compare and contrast np.mean() and np.average() functions in Numpy. When would you use one over the other?

Ans - **NumPy's `np.mean()` and `np.average()`**

Both `np.mean()` and `np.average()` are functions in NumPy used to calculate averages. However, they have subtle differences in their behavior, especially when dealing with weighted averages.

**np.mean()**
* **Simple Average:** Calculates the arithmetic mean of an array, which is the sum of all elements divided by the number of elements.
* **Syntax:** `np.mean(array, axis=None, dtype=None, out=None, keepdims=False)`

**np.average()**
* **Weighted Average:** Can calculate the weighted average if weights are provided.
* **Syntax:** `np.average(a, weights=None, axis=None, returned=False)`

**When to Use Which:**

* **np.mean():**
  - Use when you need a simple, unweighted average.
  - Ideal for quick calculations of central tendency.

* **np.average():**
  - Use when you need to calculate a weighted average.
  - Useful in statistical analysis where certain data points have more significance.

**Example:**

```python
import numpy as np

# Simple average
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)  # Output: 3.0

# Weighted average
weights = np.array([1, 2, 3, 4, 5])
weighted_average = np.average(arr, weights=weights)
print(weighted_average)  # Output: 3.6666666666666665
```

In the example above, the weighted average gives more importance to the larger numbers, as they have higher weights.

Q3 - Describe the methods for reversing a Numpy array along different axes. Provide examples for 1D and 2D arrays.

Ans - **Reversing Numpy Arrays Along Different Axes**

NumPy provides a straightforward way to reverse arrays along specific axes using array slicing and indexing.

**Reversing a 1D Array:**

To reverse a 1D array, we can simply use slicing with a step of -1:

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]
```

**Reversing a 2D Array:**

To reverse a 2D array, we can reverse along specific axes using the `[::-1]` slicing technique:

* **Reversing Rows:**
  ```python
  arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

  reversed_rows = arr[::-1, :]
  print(reversed_rows)
  ```

* **Reversing Columns:**
  ```python
  reversed_cols = arr[:, ::-1]
  print(reversed_cols)
  ```

* **Reversing Both Rows and Columns:**
  ```python
  reversed_both = arr[::-1, ::-1]
  print(reversed_both)
  ```

**Key Points:**

* **Slicing:** The `[::-1]` slicing technique is used to reverse the order of elements in an array.
* **Axis Specification:** The axis along which the reversal is performed can be specified using indexing.
* **Flexibility:** You can combine multiple reversals to achieve complex array manipulations.

By understanding these methods, you can efficiently reverse arrays along different axes to suit your specific data analysis needs.

Q4 - How can you describe the data type of elements in a Numpy array? Discuss the importance of data types in memory management and performance.

Ans - **Describing Data Types in Numpy Arrays**

NumPy arrays are homogeneous, meaning all elements in an array must have the same data type. This data type determines the kind of data stored in each element, such as integers, floating-point numbers, or complex numbers.

**To determine the data type of a Numpy array or its elements, you can use the `dtype` attribute:**

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64

arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype)  # Output: float64
```

**Importance of Data Types in Memory Management and Performance:**

1. **Memory Efficiency:**
   - **Optimal Data Type Choice:** Selecting the appropriate data type for your data can significantly impact memory usage. For example, using `int32` instead of `int64` can halve the memory footprint for integer arrays.
   - **Avoiding Unnecessary Precision:** If you don't need high precision, using a smaller data type like `float32` instead of `float64` can save memory, especially for large arrays.

2. **Performance:**
   - **Optimized Operations:** NumPy operations are optimized for specific data types. Using the correct data type can lead to faster computations.
   - **Cache Efficiency:** Smaller data types can be more cache-friendly, as they take up less memory and can be loaded into cache more efficiently.

3. **Data Integrity:**
   - **Preventing Data Loss:** Choosing the correct data type ensures that data is represented accurately without loss of precision or range.
   - **Avoiding Type Errors:** Mismatched data types can lead to unexpected results and errors during calculations.

**In Conclusion:**

Understanding and carefully selecting data types in NumPy is crucial for efficient memory usage and optimal performance. By considering the range of values, precision requirements, and memory constraints, you can choose the most suitable data type for your specific use case.

Q5 - Define ndarrays in Numpy and explain their key features. How do they differ from standard Python lists?

Ans - **Numpy ndarrays: A Powerful Tool for Numerical Computing**

In the realm of Python's scientific computing ecosystem, NumPy's ndarrays (n-dimensional arrays) stand as the cornerstone. These versatile data structures provide a high-performance, efficient, and convenient way to handle multidimensional arrays of numbers.

**Key Features of Numpy ndarrays:**

1. **Homogeneous Data Type:** Unlike Python lists, which can hold elements of diverse data types, ndarrays enforce a single, uniform data type for all elements. This homogeneity significantly enhances memory efficiency and computational speed.
2. **Multidimensional Arrays:** Ndarrays can represent data in any number of dimensions, from simple one-dimensional vectors to complex multidimensional matrices and tensors. This flexibility makes them suitable for a wide range of applications, including linear algebra, image processing, and machine learning.
3. **Vectorized Operations:** Numpy excels at performing operations on entire arrays element-wise, without the need for explicit loops. This vectorization leads to highly optimized and efficient computations.
4. **Broadcasting:** Numpy supports broadcasting, a powerful technique that allows operations between arrays of different shapes. This feature simplifies many mathematical operations, especially when dealing with scalar values or arrays of different sizes.
5. **Advanced Indexing and Slicing:** Ndarrays offer sophisticated indexing and slicing capabilities, enabling flexible access and manipulation of array elements. This includes integer indexing, boolean indexing, and fancy indexing.
6. **Efficient Memory Layout:** Ndarrays are stored in contiguous memory blocks, which improves cache locality and reduces memory access time. This design choice contributes to their performance advantage over Python lists.
7. **Integration with Other Libraries:** Numpy seamlessly integrates with other scientific computing libraries like SciPy, Matplotlib, and Pandas, forming a powerful toolset for data analysis and visualization.

**How Numpy ndarrays Differ from Python Lists:**

| Feature | Numpy ndarray | Python List |
|---|---|---|
| Data Type | Homogeneous | Heterogeneous |
| Memory Efficiency | More Efficient | Less Efficient |
| Performance | Faster for Numerical Operations | Slower for Numerical Operations |
| Vectorization | Supports Vectorized Operations | Does Not Support Vectorized Operations |
| Broadcasting | Supports Broadcasting | Does Not Support Broadcasting |
| Advanced Indexing | Advanced Indexing and Slicing | Basic Indexing and Slicing |

In summary, Numpy ndarrays provide a compelling alternative to Python lists for numerical computing tasks. Their efficiency, flexibility, and integration with other libraries make them an indispensable tool for data scientists, engineers, and researchers.

Q6 - Analyze the performance benefits of Numpy arrays over Python lists for large-scale numerical operations.

Ans - **Numpy Arrays vs. Python Lists: A Performance Deep Dive**

When it comes to large-scale numerical operations, Numpy arrays offer a significant performance advantage over Python lists. Let's delve into the reasons behind this:

**1. Memory Efficiency:**

* **Homogeneous Data Type:** Numpy arrays store elements of the same data type, allowing for efficient memory allocation and management. This reduces memory overhead compared to Python lists, which can store elements of different data types.
* **Contiguous Memory Layout:** Numpy arrays are stored in contiguous blocks of memory, which improves cache locality and reduces memory access time. Python lists, on the other hand, can be scattered across memory, leading to increased memory access costs.

**2. Vectorized Operations:**

* **Element-wise Operations:** Numpy supports vectorized operations, which allow you to perform operations on entire arrays at once, without the need for explicit loops. This leverages the power of underlying C implementations, resulting in significantly faster execution times.
* **Broadcasting:** Numpy's broadcasting feature enables operations between arrays of different shapes, further optimizing computations.

**3. Optimized C Implementation:**

* **Underlying C Code:** Numpy is built on top of optimized C code, which provides a significant performance boost over pure Python implementations. This is particularly evident in numerical operations like matrix multiplication, linear algebra, and Fourier transforms.

**Real-world Performance Comparison:**

To illustrate the performance difference, consider a simple example: multiplying two large arrays element-wise.

```python
import numpy as np
import time

# Create two large arrays
n = 1000000
a = np.random.rand(n)
b = np.random.rand(n)

# Python list approach
def python_list_multiply(a, b):
    c = []
    for i in range(n):
        c.append(a[i] * b[i])
    return c

# Numpy array approach
def numpy_array_multiply(a, b):
    return a * b

# Time the operations
start_time = time.time()
python_list_result = python_list_multiply(a, b)
python_list_time = time.time() - start_time

start_time = time.time()
numpy_array_result = numpy_array_multiply(a, b)
numpy_array_time = time.time() - start_time

print("Python list time:", python_list_time)
print("Numpy array time:", numpy_array_time)
```

When you run this code, you'll typically find that the Numpy array approach is significantly faster than the Python list approach, especially for large arrays.

Q7 - Compare vstack() and hstack() functions in Numpy. Provide examples demonstrating their usage and output.

Ans - **Numpy's vstack() and hstack(): A Comparative Analysis**

In NumPy, `vstack()` and `hstack()` are powerful functions used to stack arrays vertically and horizontally, respectively.

**vstack()**

* **Vertical Stacking:** It stacks arrays vertically, meaning it places one array below another.
* **Syntax:** `np.vstack((array1, array2, ...))`

**Example:**

```python
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

stacked_array = np.vstack((array1, array2))

print(stacked_array)
```

**Output:**

```
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
```

**hstack()**

* **Horizontal Stacking:** It stacks arrays horizontally, meaning it places one array to the right of another.
* **Syntax:** `np.hstack((array1, array2, ...))`

**Example:**

```python
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

stacked_array = np.hstack((array1, array2))

print(stacked_array)
```

**Output:**

```
[[1 2 5 6]
 [3 4 7 8]]
```

**Key Considerations:**

* **Array Shapes:** The arrays being stacked must have compatible shapes. For `vstack()`, the number of columns must be the same. For `hstack()`, the number of rows must be the same.
* **Data Types:** The arrays should have the same data type or compatible data types for efficient stacking.

By understanding the differences between `vstack()` and `hstack()`, you can effectively manipulate arrays to create new structures that suit your specific needs in numerical computations and data analysis.

Q8 - Explain the differences between fliplr() and flipud() methods in Numpy, including their effects on various array dimensions.

Ans - **Understanding fliplr() and flipud() in NumPy**

NumPy provides two functions, `fliplr()` and `flipud()`, for flipping arrays along specific axes. Let's break down their differences:

**fliplr()**

* **Flips the array horizontally.**
* **Reverses the order of elements along the second axis (axis=1).**
* **For 2D arrays, it flips the columns.**
* **For higher-dimensional arrays, it flips the second-to-last dimension.**

**Example:**

```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_arr = np.fliplr(arr)
print(flipped_arr)
```

**Output:**

```
[[3 2 1]
 [6 5 4]]
```

**flipud()**

* **Flips the array vertically.**
* **Reverses the order of elements along the first axis (axis=0).**
* **For 2D arrays, it flips the rows.**
* **For higher-dimensional arrays, it flips the first dimension.**

**Example:**

```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_arr = np.flipud(arr)
print(flipped_arr)
```

**Output:**

```
[[4 5 6]
 [1 2 3]]
```

**Key Differences:**

| Function | Axis | Effect |
|---|---|---|
| `fliplr()` | 1 (second-to-last) | Flips horizontally |
| `flipud()` | 0 (first) | Flips vertically |

**Visual Representation:**

```
Original Array:
[[1 2 3]
 [4 5 6]]

fliplr():
[[3 2 1]
 [6 5 4]]

flipud():
[[4 5 6]
 [1 2 3]]
```

**In essence:**

* `fliplr()` is like flipping a book horizontally.
* `flipud()` is like flipping a book vertically.

By understanding these functions, you can manipulate arrays effectively in various data processing and analysis tasks.


Q9 - Discuss the functionality of the array_split() method in Numpy. How does it handle uneven splits?

Ans - **Numpy's `array_split()` Method**

The `array_split()` function in NumPy is a versatile tool for dividing an array into multiple sub-arrays. It's particularly useful when you need to split an array into a specific number of sub-arrays, regardless of whether the split is even or uneven.

**How it Works:**

1. **Input:**
   - The array to be split.
   - The desired number of splits (as an integer).

2. **Output:**
   - A list of sub-arrays.

**Handling Uneven Splits:**

When the array cannot be evenly divided into the specified number of sub-arrays, `array_split()` handles the unevenness intelligently:

- **Even Split:** If the array's length is evenly divisible by the number of splits, each sub-array will have the same size.
- **Uneven Split:** If the array's length is not evenly divisible, the sub-arrays will have approximately equal sizes, but the last sub-array might be slightly larger or smaller to accommodate the remainder.

**Example:**

```python
import numpy as np

arr = np.arange(11)

# Even split into 4 sub-arrays
split_arr1 = np.array_split(arr, 4)
print(split_arr1)

# Uneven split into 3 sub-arrays
split_arr2 = np.array_split(arr, 3)
print(split_arr2)
```

**Output:**

```
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10])]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]
```

As you can see, in the second example, the first two sub-arrays have 4 elements each, while the last one has 3 to accommodate the total length of 11.

**Key Points:**

- `array_split()` is flexible and can handle both even and uneven splits.
- The output is a list of arrays, which can be useful for parallel processing or other applications.
- For more granular control over splitting, consider using `split()` or `hsplit()` for horizontal splitting and `vsplit()` for vertical splitting.

By understanding the behavior of `array_split()`, you can efficiently divide your NumPy arrays into smaller chunks for various data processing tasks.


Q10 - Explain the concepts of vectorization and broadcasting in Numpy. How do they contribute to efficient array operations?

Ans - **Vectorization and Broadcasting in NumPy**

NumPy, a powerful library for numerical computations in Python, leverages two key concepts, vectorization and broadcasting, to significantly enhance the efficiency of array operations.

**Vectorization**

Vectorization is a technique that replaces explicit loops with optimized array operations. It allows NumPy to perform operations on entire arrays element-wise, without the need for explicit Python loops. This leads to a significant performance boost, as these operations are often implemented in highly optimized C code.

**Example:**

```python
import numpy as np

# Vectorized approach
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Element-wise addition

# Equivalent loop-based approach (less efficient)
c = np.zeros_like(a)
for i in range(len(a)):
    c[i] = a[i] + b[i]
```

In the vectorized approach, the addition operation is performed on entire arrays in a single step, which is much faster than the loop-based approach.

**Broadcasting**

Broadcasting is a powerful feature that allows NumPy to perform operations on arrays with different shapes, as long as certain conditions are met. NumPy automatically expands the dimensions of smaller arrays to match the shape of the larger array, enabling operations between arrays of different sizes.

**Rules for Broadcasting:**

1. **Shape Compatibility:** The arrays must be compatible in shape. This means that either their shapes are identical, or one of them has a shape of 1 in a particular dimension.
2. **Dimension Expansion:** If the shapes are not identical, the smaller array is stretched or broadcast to match the shape of the larger array.
3. **Broadcasting Direction:** Broadcasting occurs along the leading dimensions.

**Example:**

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

c = a * b  # Broadcasting b to match the shape of a
```

In this example, the array `b` is broadcast to match the shape of `a`, and the multiplication is performed element-wise.

**Benefits of Vectorization and Broadcasting:**

- **Performance:** By eliminating Python loops, vectorization and broadcasting significantly improve the performance of array operations.
- **Readability:** Vectorized operations often lead to more concise and readable code.
- **Conciseness:** Broadcasting allows you to perform complex operations on arrays of different shapes without explicit loops or reshaping.

By understanding and effectively utilizing vectorization and broadcasting, you can write efficient and elegant NumPy code for a wide range of numerical computations.


## Practical Questions :

Q1 - Create a 3x3 Numpy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(array)

# Interchange rows and columns using the transpose operation
transposed_array = array.T

print("\nTransposed array (rows and columns interchanged):")
print(transposed_array)

Original array:
[[43 90 13]
 [73 52 74]
 [ 3 23 48]]

Transposed array (rows and columns interchanged):
[[43 73  3]
 [90 52 23]
 [13 74 48]]


Q2 - Generate a 1D Numpy array with 10 elements. Reshape it into a 2x5 array, then into 5x2 array.

In [ ]:
import numpy as np

# Create a 1D array with 10 elements
array = np.random.randint(1, 101, size=10)

print("Original 1D array:")
print(array)

# Reshape into a 2x5 array
array_2x5 = array.reshape(2, 5)

print("\nReshaped 2x5 array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array.reshape(5, 2)

print("\nReshaped 5x2 array:")
print(array_5x2)

Original 1D array:
[79 34 90 94 36 32 69 95 84 81]

Reshaped 2x5 array:
[[79 34 90 94 36]
 [32 69 95 84 81]]

Reshaped 5x2 array:
[[79 34]
 [90 94]
 [36 32]
 [69 95]
 [84 81]]


Q3 - Create a 4x4 Numpy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
import numpy as np

# Create a 4x4 array with random float values
array = np.random.rand(4, 4)

# Add a border of zeros
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print("Original array:")
print(array)

print("\nArray with zero border:")
print(array_with_border)

Original array:
[[0.26028065 0.83062092 0.7492325  0.13989013]
 [0.42348251 0.69566343 0.88886928 0.49424165]
 [0.75351984 0.51837342 0.08049012 0.68172468]
 [0.68854213 0.17643922 0.9108773  0.70134037]]

Array with zero border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.26028065 0.83062092 0.7492325  0.13989013 0.        ]
 [0.         0.42348251 0.69566343 0.88886928 0.49424165 0.        ]
 [0.         0.75351984 0.51837342 0.08049012 0.68172468 0.        ]
 [0.         0.68854213 0.17643922 0.9108773  0.70134037 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4 - Using Numpy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np

array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


Q5 - Create a Numpy array of strings ['python','numpy','pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [ ]:
import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

# Uppercase
upper_arr = np.char.upper(arr)
print("Uppercase:", upper_arr)

# Lowercase
lower_arr = np.char.lower(arr)
print("Lowercase:", lower_arr)

# Title case
title_arr = np.char.title(arr)
print("Title case:", title_arr)

# Swapcase
swap_arr = np.char.swapcase(arr)
print("Swapcase:", swap_arr)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Swapcase: ['PYTHON' 'NUMPY' 'PANDAS']


Q6 - Generate a Numpy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np

# Original array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert space between each character
spaced_arr = np.char.join(' ', arr)
print(spaced_arr)


['p y t h o n' 'n u m p y' 'p a n d a s']


Q7 - Create two 2D Numpy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition = arr1 + arr2
print("Addition:\n", addition)

# Element-wise subtraction
subtraction = arr1 - arr2
print("Subtraction:\n", subtraction)

# Element-wise multiplication
multiplication = arr1 * arr2
print("Multiplication:\n", multiplication)

# Element-wise division
division = arr1 / arr2
print("Division:\n", division)

Addition:
 [[7 7 7]
 [7 7 7]]
Subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]
Multiplication:
 [[ 6 10 12]
 [12 10  6]]
Division:
 [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


Q8 - Use Numpy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:\n", identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


Q9 - Generate a Numpy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [ ]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, size=100)
print("Array of random integers:\n", arr)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
primes = arr[np.vectorize(is_prime)(arr)]
print("Prime numbers in the array:\n", primes)

Array of random integers:
 [817 441 452 293  86 594 259 310 963 527  79 446 472  76 694 593  65 382
 800 306 583 321  90 104 974 292  82 343  71 645 665 416 570 855 276 796
 332 410 281 740  81 315 228 785 848  53 156 631 905 529   2 576 862 341
 156 259 898 994 175 385 759 762 528 750 860 275 557 742 213 584 359 988
 187 475 996 258 645 200 113 843  19 547 652 600  81 503 555 522 681  38
 534 106 967 892 204 768 211 849 679  45]
Prime numbers in the array:
 [293  79 593  71 281  53 631   2 557 359 113  19 547 503 967 211]


Q10 - Create a Numpy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
import numpy as np

# Generate a NumPy array of 30 random daily temperatures (e.g., between 20 and 35 degrees Celsius)
temperatures = np.random.randint(20, 36, size=30)
print("Daily Temperatures:\n", temperatures)

# Calculate weekly averages (4 weeks, assuming 7 days each, and 2 days left for a 30-day month)
weekly_averages = [np.mean(temperatures[i:i+7]) for i in range(0, 28, 7)]
remaining_days_average = np.mean(temperatures[28:])

# Display weekly averages and remaining days average
print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages, start=1):
    print(f"Week {i} Average: {avg:.2f}")

print(f"\nRemaining Days Average: {remaining_days_average:.2f}")

Daily Temperatures:
 [34 33 27 30 24 30 35 32 24 29 27 24 20 23 30 33 24 31 34 33 33 30 25 35
 22 34 35 29 29 34]

Weekly Averages:
Week 1 Average: 30.43
Week 2 Average: 25.57
Week 3 Average: 31.14
Week 4 Average: 30.00

Remaining Days Average: 31.50
